

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  CGO_ENABLED: '0'
  GOOS: 'linux'
  GOARCH:  'amd64'
  containerRepository: ''  


steps: 
  - task: GoTool@0
    inputs:
      version: '1.16.13'
    displayName: "Setup Golang env"
  - task: Go@0
    inputs:
      command: 'get' 
      arguments: '-d'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: "Get Dependencies"
  - task: Go@0
    inputs:
      command: 'test'
      arguments: "-v ./..."
      workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: "Test application"
  - task: Go@0
    inputs:
      command: 'build'
      arguments: '-a -o _output/app'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: "Build application"
  - task: Docker@2
    inputs:
      command: buildAndPush
      repository: ${var.containerRepository}
      containerRegistry: ${var.containerRegistry}
      Dockerfile: "**/Containerfile"

      